import {StyleSheet, Platform} from 'react-native';

const styles = StyleSheet.create({
 root:          { flex: 1 },
  scrollContent: { paddingHorizontal: 14, paddingTop: 12 },

  // Contact Header
  contactHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#0C0F1A',
    borderRadius: 18,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#111827',
    gap: 14,
  },
  avatarOuter: {
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.45,
    shadowRadius: 14,
    elevation: 8,
  },
  avatarRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 2.5,
    overflow: 'hidden',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarImg: { width: 64, height: 64, borderRadius: 32 },
  avatarFallback: {
    width: 64,
    height: 64,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitial: { fontSize: 26, fontWeight: '900' },
  contactInfo:   { flex: 1 },
  contactName:   { fontSize: 17, fontWeight: '800', color: '#E8EDF5', marginBottom: 2 },
  contactPhone:  { fontSize: 11, color: '#3D4E6A', marginBottom: 7 },
  stressLevelPill: {
    alignSelf: 'flex-start',
    borderRadius: 20,
    borderWidth: 1,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  stressLevelText: { fontSize: 12, fontWeight: '700' },

  // Alert Banner
  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    paddingVertical: 9,
    paddingHorizontal: 13,
    marginBottom: 9,
    gap: 7,
  },
  bannerIcon: { fontSize: 14 },
  bannerText: { fontWeight: '700', fontSize: 12, letterSpacing: 0.4, flex: 1 },

  // Gauge Card
  gaugeCard: {
    marginVertical: 10,
    backgroundColor: '#080B14',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#1A2235',
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 14,
    elevation: 10,
  },
  gaugeAccentBar:   { height: 3 },
  gaugeCircleWrap:  { alignItems: 'center', paddingTop: 24, paddingBottom: 20 },
  gaugeOuterRing: {
    width: 180, height: 180, borderRadius: 90,
    borderWidth: 3,
    alignItems: 'center', justifyContent: 'center',
    backgroundColor: '#060810',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.9,
    shadowRadius: 18,
    elevation: 12,
  },
  gaugeInner:       { alignItems: 'center' },
  gaugeEmoji:       { fontSize: 28, marginBottom: 1 },
  gaugeScore:       { fontSize: 54, fontWeight: '900', lineHeight: 58 },
  gaugeScoreUnit:   { fontSize: 9, color: '#3D4E6A', letterSpacing: 1.5, textTransform: 'uppercase', marginTop: 1 },
  gaugeStatePill: {
    flexDirection: 'row', alignItems: 'center',
    borderRadius: 20, paddingHorizontal: 10, paddingVertical: 3,
    borderWidth: 1, marginTop: 6,
  },
  gaugeStateLabel:  { fontSize: 11, fontWeight: '700', letterSpacing: 0.4 },
  // Stats strip
  gaugeStatsStrip: {
    flexDirection: 'row',
    borderTopWidth: 1, borderBottomWidth: 1,
    borderColor: '#111827',
  },
  gaugeStatItem:  { flex: 1, alignItems: 'center', paddingVertical: 12 },
  gaugeStatVal:   { fontSize: 14, fontWeight: '800', color: '#E8EDF5' },
  gaugeStatKey:   { fontSize: 8, color: '#3D4E6A', letterSpacing: 1.3, textTransform: 'uppercase', marginTop: 2 },
  gaugeStatSep:   { width: 1, backgroundColor: '#111827', marginVertical: 8 },
  // Zone bar
  gaugeZoneWrap:        { padding: 14  },
  gaugeZoneHeaderRow:   { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 9 },
  gaugeZoneHeaderLabel: { fontSize: 10, color: '#3D4E6A', letterSpacing: 1.3, textTransform: 'uppercase', fontWeight: '700' },
  gaugeZoneHeaderPct:   { fontSize: 13, fontWeight: '800' },
  gaugeSegBar:          { flexDirection: 'row', gap: 3 },
  gaugeSegSlot:         { flex: 1 },
  gaugeSegTrack:        { height: 10, borderRadius: 5, overflow: 'hidden' },
  gaugeSegFill:         { height: '100%', borderRadius: 5 },
  gaugeTickRow:         { flexDirection: 'row', justifyContent: 'space-between', marginTop: 5 },
  gaugeTick:            { fontSize: 8, color: '#3D4E6A', fontWeight: '600' },
  gaugeZoneLegend:      { flexDirection: 'row', justifyContent: 'space-between', marginTop: 9 },
  gaugeZoneLegendItem:  { flexDirection: 'row', alignItems: 'center', gap: 4 },
  gaugeZoneLegendDot:   { width: 6, height: 6, borderRadius: 3 },
  gaugeZoneLegendText:  { fontSize: 8, color: '#3D4E6A', fontWeight: '600' },

  // BPM Hero
  bpmHero: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: '#0C0F1A',
    borderRadius: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#111827',
  },
  bpmHeroLeft:  { flex: 1 },
  bpmHeroLabel: { fontSize: 10, color: '#3D4E6A', letterSpacing: 1.4, textTransform: 'uppercase', marginBottom: 4 },
  bpmValRow:    { flexDirection: 'row', alignItems: 'flex-end', gap: 4 },
  bpmVal:       { fontSize: 50, fontWeight: '900', lineHeight: 54 },
  bpmUnit:      { fontSize: 15, color: '#3D4E6A', fontWeight: '600', marginBottom: 6 },
  bpmMeta:      { fontSize: 11, color: '#3D4E6A', marginTop: 3 },
  bpmHeroRight: { paddingLeft: 12, alignItems: 'center', gap: 8 },
  bpmPulseRing: { width: 56, height: 56, borderRadius: 28, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  bpmPulseIcon: { fontSize: 24 },
  liveBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#00E5A012',
    borderRadius: 6,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderWidth: 1,
    borderColor: '#00E5A030',
    gap: 4,
  },
  liveDot:  { width: 5, height: 5, borderRadius: 2.5, backgroundColor: '#00E5A0' },
  liveText: { fontSize: 8, color: '#00E5A0', fontWeight: '800', letterSpacing: 1 },

  // Metric Grid
  grid:        { flexDirection: 'row', gap: 8, marginBottom: 10 },
  metricCard: {
    flex: 1,
    backgroundColor: '#0C0F1A',
    borderRadius: 14,
    padding: 12,
    borderWidth: 1,
    borderColor: '#111827',
    alignItems: 'center',
  },
  metricIconWrap: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 6 },
  metricIcon:  { fontSize: 18 },
  metricValue: { fontSize: 20, fontWeight: '800' },
  metricUnit:  { fontSize: 11, color: '#3D4E6A', fontWeight: '400' },
  metricLabel: { fontSize: 9, color: '#3D4E6A', marginTop: 2, textTransform: 'uppercase', letterSpacing: 1 },
  metricSub:   { fontSize: 10, fontWeight: '600', marginTop: 3 },

  // Section
  section: {
    backgroundColor: '#0C0F1A',
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#111827',
  },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  sectionTitle:  { fontSize: 13, fontWeight: '700', color: '#E8EDF5', letterSpacing: 0.3 },
  sectionDesc:   { fontSize: 11, color: '#3D4E6A', marginBottom: 11, lineHeight: 17 },
  scorePill:     { flexDirection: 'row', alignItems: 'center', borderRadius: 20, paddingHorizontal: 8, paddingVertical: 3, borderWidth: 1 },
  scorePillText: { fontSize: 11, fontWeight: '800' },

  // Breakdown Bars
  barRow:     { flexDirection: 'row', alignItems: 'center', marginBottom: 11, gap: 10 },
  barIconWrap:{ width: 32, height: 32, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  barIcon:    { fontSize: 15 },
  barContent: { flex: 1 },
  barTopRow:  { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 5 },
  barLabel:   { fontSize: 12, color: '#E8EDF5', fontWeight: '600' },
  barTrack:   { height: 5, backgroundColor: '#1A2235', borderRadius: 3, overflow: 'hidden' },
  barFill:    { height: 5, borderRadius: 3 },
  barScore:   { fontSize: 12, fontWeight: '800' },
  barMax:     { fontSize: 10, color: '#3D4E6A', fontWeight: '400' },
  barPct:     { fontSize: 9, marginTop: 4, letterSpacing: 0.3 },

  // Tip
  tipCard: {
    flexDirection: 'row',
    backgroundColor: '#0C0F1A',
    borderRadius: 16,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: '#111827',
    gap: 12,
    alignItems: 'flex-start',
  },
  tipIcon:  { fontSize: 20, marginTop: 2 },
  tipBody:  { flex: 1 },
  tipTitle: { fontSize: 12, fontWeight: '700', color: '#E8EDF5', marginBottom: 4 },
  tipText:  { color: '#A0AEC0', fontSize: 12, lineHeight: 18 },

  // Action Buttons
  actionRow: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 10,
  },
  actionBtn: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 10,
    paddingVertical: 7,
    gap: 5,
    borderWidth: 1,
  },
  actionBtnChat: {
    backgroundColor: '#4A90FF18',
    borderColor: '#4A90FF40',
  },
  actionBtnAudio: {
    backgroundColor: '#00E5A018',
    borderColor: '#00E5A040',
  },
  actionBtnHeart: {
    backgroundColor: '#FF336618',
    borderColor: '#FF336640',
  },
  actionBtnPressed: {
    opacity: 0.6,
  },
  actionBtnLabel: {
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
});

export default styles;
