
auth.token=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

defaults.org=john-vision-3f
defaults.project=react-native-ios

defaults.url=https://sentry.io/
