export const locations = [
   {id:1,name: 'Assaba'},
   {id:2,name: 'Brakna'},
   {id:3,name: 'Dakhlet Nouadhibou'},
   {id:4,name: 'Gorgol'},
   {id:5,name: 'Guidimaka'},
   {id:6,name: 'Hodh Ech Chargui'},
   {id:7,name: 'Hodh El Gharbi'},
   {id:8,name: 'Inchiri'},
   {id:9,name: 'Nouakchott'},
   {id:10,name: 'Tagant'},
   {id:11,name: 'Tiris Zemmour'},
   {id:12,name: 'Trarza'},
   {id:13,name: 'Wilaya du Brakna'},
   {id:14,name: 'Wilaya du Gorgol'},
]